### PR TITLE
Contributing a CBH (crown base height) estimation algorithm (Luo et al. 2018).

### PR DESCRIPTION
**Pull request by mavavilj**
Contributing a CBH (crown base height) estimation algorithm (Luo et al. 2018, https://www.osapublishing.org/oe/fulltext.cfm?uri=oe-26-10-A562&id=385987).

May be further developed based on user experience, but is usable currently, given a suitable point cloud.

### CODE REVIEW

**Comment by Jean-Romain** [comment]
I really appreciate your tentative to include a new algorithm in lidR and I'm keen to accept it. But introducing new code in an R package does not consists only in putting a standalone R script in a new file. It must be integrated, documented, validated, tested and follow R package rules which is not the case of your code. Moreover I see

```r
library(TreeLS)
library(pracma)
library(equate)
```

Which means that 3 more dependencies must be added in lidR which is a definitive no on my side. Can you write a code without these packages? If not you will have to create a new package on your own but you can create a [lidR plugins](https://jean-romain.github.io/lidRbook/plugins.html) if you want.

**Comment by mavavilj** [comment]
I thought it would satisfy requirements for a "one function file":

https://r-pkgs.org/r.html#code-organising

And I was comparing it to this one in the repo:

https://github.com/r-lidar/lidR/blob/master/R/concaveman.R

I will try to see if can be done without requiring those packages. Maybe, maybe not.

**Comment by Jean-Romain** [comment]
> I thought it would satisfy requirements for a "one function file":

This is not about being in one file. It's about your function not being documented, not being exported, using invalid statements in the code of an R package (use of `library` or `:::` operator), without being unit-tested, without calling functions by namespace and so on.

> Maybe, maybe not. I thought TreeLS is closely related to lidR, so that I could use it:

`TreeLS` is not on CRAN and cannot be a dependency of lidR. And even if it were `TreeLS` depends on `lidR` so `lidR` cannot depends on `TreeLS` (cyclic dependency)

> I can put it into lidRplugins if it's better.

The problems I'm highlighting must be resolved first.

**Comment by mavavilj** [comment]
I don't know if you've discussed with the TreeLS author though, because it seems that these projects have quite a bit of overlap. With TreeLS being more geared towards trees, which might mean that it's actually the better place for this function. But lidR does have some segmentation methods.

**Comment by Jean-Romain** [comment]
I personally know the guy behind TreeLS. I do not have new from him but last time we exchanged he said that he was no longer working with lidar.  His package was removed from CRAN 1 years ago because he never fixed troubleshooting on CRAN. There is no chance the package will comeback imo. He never answered a single issue on his github for months. The project is abandoned. Here your 3 best option:

- Integration in `lidR` if you can remove dependencies and write almost valid code for an R package
- Integration in `lidRplugins`. We can add dependencies but your code will never go on CRAN
- Your own package that uses or not lidR as you wish. If your plan is to release the code from github you can depends on `TreeLS` as a remote dependency. If your plan is to release on CRAN you must not depend on `TreeLS`

**Comment by mavavilj** [comment]
Okay, I will see what I can do. I'm aiming for the first one, but I'm not sure if unit testing is trivial for such a function (do you have any ideas how to unit test on point clouds?). It's not possible to test it on all kinds of inputs anyways, so it should leave the verification of results up to the user.

**Comment by bi0m3trics** [comment]
I just glanced at the code (ok, looked line by line) and failed to see a TreeLS function (I'm pretty familiar with that code and package), so I must have missed it. What TreeLS function(s) are you using?

**Comment by Jean-Romain** [comment]
> (do you have any ideas how to unit test on point clouds?

Run on an example data where you are sure it works as expected. Test how many tree are found. Test if errors are properly handled. Test if weird parameters trigger warning or error. Take inspiration of https://github.com/r-lidar/lidR/blob/devel/tests/testthat/test-segment_trees.R

If your function is a tree segmentation function it must be compatible with `segment_trees`. I can help for this step.

**Comment by Jean-Romain** [comment]
Last but not least I'm only accepting algorithms that are decently fast.

**Comment by mavavilj** [comment]
> I just glanced at the code (ok, looked line by line) and failed to see a TreeLS function (I'm pretty familiar with that code and package), so I must have missed it. What TreeLS function(s) are you using?

https://www.rdocumentation.org/packages/TreeLS/versions/2.0.2/topics/readTLS

> > (do you have any ideas how to unit test on point clouds?
> 
> Run on an example data where you are sure it works as expected. Test how many tree are found. Test if errors are properly handled. Test if weird parameters trigger warning or error. Take inspiration of https://github.com/r-lidar/lidR/blob/devel/tests/testthat/test-segment_trees.R
> 
> If your function is a tree segmentation function it must be compatible with `segment_trees`. I can help for this step.

Did you even read what the code does? It operates on a single tree point cloud. But based on my experiments it can produce wildly varying results depending on the quality of input (quality of segmentation, quality of separation from understory vegetation, point density, ...).

The reason I asked is that testing "robustness" of this is non-trivial. But I've already tried to cover the error cases.

**Comment by Jean-Romain** [comment]
`TreeLS::readTLS` is only a warpper around `lidR::readLAS` + a wrapper around `data.table::fread` and `lidR::LAS`.

> Did you even read what the code does? 

No, I've only seen that in many places the code is not  a valid R code for an R package according to CRAN policy. Actually it is very hard to understand what it does just reading the code on github. I need to read the article first. Remember that your code is not documented so I was not able to refer to the doc or to a reproducible example. So I don't even know what it does.

> The reason I asked is that testing "robustness" of this is non-trivial.

The goal is not to test robustness of tree detection method. I presume you ran testing for your article.  The goal if  to test if the output is always the same and that code modifications do not break anything, to test if the function does not crash unexpectedly especially in edge cases, to test if the function returns the errors it is expected to thrown and so on

**Comment by mavavilj** [comment]
`readTLS` is the example used for reading data in (Line 21):

https://github.com/r-lidar/lidR/pull/506/files#diff-c247f3a6f16f12ee6eb80aaea88009eba95d3c194f7c2e30d55b43f92f9313bcR21

Yes, but I find that it's also non-trivial to know all the cases where the algorithm could fail. It could fail e.g. inside some external function used to process derivatives. Unless these are fully tested as well.

I've recognized some of them, but I'm not entirely sure, if I've recognized all of them. The paper does not explain the exceptions that might occur in code. But some of them are related to e.g. "0 point intervals" that might occur in some cases where the point cloud is sparse at places.

**Comment by mavavilj** [comment]
Can you clarify which of the CRAN conventions apply to this one function.
I assume I'm not required to produce the equivalent of it for a "full package", since I only have one function.

Do I e.g. need package metadata?

https://r-pkgs.org/description.html

**Comment by Jean-Romain** [comment]
First link. The `DESCRIPTION` file is the metadata of the package. You should never touch it. Your function must be associated with roxygen comments to generate the package manual. You can look at the other R files of the package for examples. If it is not perfect it is ok, I can fix some errors.

**Comment by mavavilj** [comment]
What should I do with the findzeros() from pracma? How am I supposed to replace it w/o relying on a new dependency?

**Comment by Jean-Romain** [comment]
Copy pasting the code from `pracma` is not a desirable way for sure. I quickly looked into the paper especially figure 4 and the problem to solve is easy. It's a 10 lines of code problem and I think using `findzeros` is overkill. Especially in your code the following is overkill and unnecessarily slow

```r
pred <- function(x) stats:::predict.smooth.spline(fit, x)$y
pred1stderiv <- function(x)  stats:::predict.smooth.spline(fit, x, deriv=1)$y
pred2ndderiv <- function(x)  stats:::predict.smooth.spline(fit, x, deriv=2)$y
```

It could become something like

```r
x <- seq(0, 30, 0.5)
pred <- stats::predict.smooth.spline(fit, x)$y
pred1stderiv <-  stats::predict.smooth.spline(fit, x, deriv=1)$y
pred2ndderiv <-  stats:::predict.smooth.spline(fit, x, deriv=2)$y

for (i in 2:length(pred2ndderiv)) {
  if (sign(pred2ndderiv[i-1]) != sign(pred2ndderiv[i]))
    # There is a 0 approximately at (x[i-1] + x[i])/2
}
```

Aldo by looking at the paper I know understand that we are talking about a metrics derived for each tree after a tree segmentation. Consequently your code should be compliant with the "metrics" concept of lidR and should work somehow like this:

```r
tree_metrics(las, func = ~cbh_lu02008(X,Y,Z))
```

**Comment by mavavilj** [comment]
How do you know your proposition is more efficient?

**Comment by mavavilj** [comment]
Actually, I'm not sure anymore, if I want to do the work for this, since I've been thinking that Nim would be better technology for point cloud analysis.

**Comment by hriihimaki** [comment]
Before doing that you should ask yourself a question - who (else) in the point cloud industry uses nim? 

If you want to go native why not C++?

Just my two cents ...

**Comment by mavavilj** [comment]
> Before doing that you should ask yourself a question - who (else) in the point cloud industry uses nim?
> 
> If you want to go native why not C++?
> 
> Just my two cents ...

A way to make it appear viable is to contribute towards it. I find it's a great improvement over C++ and it also has features that make it feel like Java or Python. But it's as fast as C/C++.

**Comment by Jean-Romain** [comment]
>  I read some paper that argued that lidR will always be considerably slower compared to more native languages. Which will presumably be a bottleneck for very large data sets.

References please ? It not completely wrong btw.

**Comment by mavavilj** [comment]
> > I read some paper that argued that lidR will always be considerably slower compared to more native languages. Which will presumably be a bottleneck for very large data sets.
> 
> References please? It is not completely wrong btw.

https://reader.elsevier.com/reader/sd/pii/S0034425720304314?token=02ED1D1CA25007E10028213AF0DF7D1AA1040772C6A17A71CBEF4E1ABF7631A26BB8996D586123C6C06F445DBCC73749&originRegion=eu-west-1&originCreation=20220203172918

**Comment by bi0m3trics** [comment]
LOL... you realizes that's @Jean-Romain et al's paper (mine too), right? He and I did the benchmarks I I think it does well, besides anything with a scripting component (i.e., passed to and not in native c/c++ or fortan or java) will be slower than most lower-level programming languages. However, I've been a lidR user since the beginning and I've tried almost everything else and the functionality and scalability of lidR consistently impresses even me!

Also, we saw no hinderances using lidR for estimating canopy fuels metrics: 
Caden P. Chamberlain, Andrew J. Sánchez Meador, Andrea E. Thode. 2021. Airborne lidar provides reliable estimates of canopy base height and canopy bulk density in southwestern ponderosa pine forests. Forest Ecology and Management. 481: 118695
https://doi.org/10.1016/j.foreco.2020.118695.

**Comment by Jean-Romain** [comment]
Well, citing the paper we wrote to argue that lidR is considerably slower than other options is... audacious... at least. Moreover referring to one specific algorithm from the peer-reviewed literature for which none of us are authors is kind of unfair cherry picking. As @bi0m3trics said he ran the benchmarks for the paper and lidR is very decent even if it has some intrinsic limitations compared to native C++ tools such as `LAStools`. I'm the first one to knowledge about that.

Anyway it is your choice to chose to move somewhere else and I won't argue against that. I appreciated you thought about lidR for sharing your code even if you do not finalize the implementation because of the constraints I put.

**Pull request closed without merging**
