### PR TITLE
Use autoconf to generate Makevars at install time

### LINKED ISSUE #786: Cannot install lidR on R 3.6.3 due to cpp 14+ requirements
# Problem

Attempting to install lidR on R 3.6.3 yields the following errors:
```
In file included from concaveman/concaveman.h:24,
                 from convaveman.cpp:2:
concaveman/rtree.h: In member function ‘void rtree<T, DIM, MAX_CHILDREN, DATA>::insert(rtree<T, DIM, MAX_CHILDREN, DATA>::data_type, const bounds_type&)’:
concaveman/rtree.h:44:21: error: ‘make_unique’ is not a member of ‘std’
   44 |       auto r = std::make_unique<type>(data, bounds);
      |                     ^~~~~~~~~~~
concaveman/rtree.h:44:21: note: ‘std::make_unique’ is only available from C++14 onwards
concaveman/rtree.h:44:37: error: expected primary-expression before ‘>’ token
   44 |       auto r = std::make_unique<type>(data, bounds);
      |                                     ^
concaveman/rtree.h:67:22: error: ‘make_unique’ is not a member of ‘std’
   67 |     auto leaf = std::make_unique<type>(best_child.get().data(), best_child.get().bounds());
      |                      ^~~~~~~~~~~
concaveman/rtree.h:67:22: note: ‘std::make_unique’ is only available from C++14 onwards
concaveman/rtree.h:67:38: error: expected primary-expression before ‘>’ token
   67 |     auto leaf = std::make_unique<type>(best_child.get().data(), best_child.get().bounds());
      |                                      ^
make: *** [/usr/lib/R/etc/Makeconf:177: convaveman.o] Error 1
ERROR: compilation failed for package ‘lidR’
* removing ‘/home/qbowers/R/x86_64-pc-linux-gnu-library/3.6/lidR’
```

# Steps to Reproduce

1. Install lidR dependencies per the README
    - `sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable`
    - `sudo apt-get update`
    - `sudo apt-get install libgdal-dev libgeos++-dev libudunits2-dev libproj-dev libx11-dev libgl1-mesa-dev libglu1-mesa-dev libfreetype6-dev libxt-dev libfftw3-dev`
2. Install the `terra` package from R-Universe (the CRAN version similarly does not install on R 3.6.3)
    - `install.packages('terra', repos='https://rspatial.r-universe.dev')`
3. Install `lidR`
    - `packages.install('lidR')`

# My Setup

- OS: Ubuntu 20.04
- R: 3.6.3

# Commentary

I know that 3.6.3 is reasonably out of date, however the lidR CRAN package still claims to support R versions as old as 3.5. Ideally a user should not have to look up the history of R's default compiler settings to install a package if it claims to be supported. Would it be possible to either change the CRAN package to report that it only supports R 4+, or else add back the C++ version requirements somewhere, perhaps as described [here](https://www.tidyverse.org/blog/2023/03/cran-checks-compiled-code/)?

Thanks!

### PR DESCRIPTION
**Pull request by quinn-r88**
This PR adds a new `configure` script to the package, which will generate Makevar files when the package is installed. The `configure` script is generated by GNU autoconf from `configure.ac`, and must be regenerated by the developer when `configure.ac` is modified.

This PR also adds a `cleanup` script, which R will use to remove the files that `configure` will generate.

Resolves #786 

## References:
- https://www.tidyverse.org/blog/2023/03/cran-checks-compiled-code/
- https://github.com/tidyverse/readxl/pull/722
- https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#C-standards
- https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Using-C_002b_002b-code

### CODE REVIEW

**Comment by quinn-r88** [comment]
hmmmmm. I don't have super convenient access to a windows cpu to debug this. How can I find the logs for these runs?

**Comment by Jean-Romain** [comment]
Me neither

https://github.com/r-lidar/lidR/actions/runs/11802549228/job/33612239436?pr=787

**Comment by Jean-Romain** [comment]
The solution is there, I remember:

https://github.com/R-ArcGIS/arcgisutils/commit/17b2520607370ab980d3d108a50e85ff59cf0fb6#diff-618cd5b83d62060ba3d027e314a21ceaf75d36067ff820db126642944145393eR4

**Comment by quinn-r88** [comment]
jeez, how silly. Thank for finding that fix! Rebased, give it a look when you can please

**Comment by Jean-Romain** [comment]
For your information I reverted your PR. I merged it but never actually used it on my machine. Yesterday I did the pull and my code dramatically slowed down and stuff than run in 1 minutes started to run in 6 minutes like if OpenMP was desactivated.  Compilation directives seem to include OpenMP and I do not have time to investigate. Thus I reverted the PR

**Pull request merged**
